[package]
name = "cards"
version = "0.0.0"
description = "All card definitions and associated card helpers"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
enumset = "1.0.8"
once_cell = "1.8.0"
rand = "0.8.4"

model = { path = "../model", version = "0.0.0" }
