[package]
name = "display"
version = "0.0.0"
description = "Converts internal game state representation into a format the client can understand"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
diff-struct = "0.4.0"

cards = { path = "../cards", version = "0.0.0" }
model = { path = "../model", version = "0.0.0" }
protos = { path = "../protos", version = "0.0.0" }
