[package]
name = "display"
version = "0.0.0"
description = "Converts internal game state representation into a format the client can understand"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
tracing = { version = "0.1.29", features = ["max_level_debug", "release_max_level_warn"] }

rules = { path = "../rules", version = "0.0.0" }
data = { path = "../data", version = "0.0.0" }
protos = { path = "../protos", version = "0.0.0" }
