[package]
name = "rules"
version = "0.0.0"
description = "All card definitions and associated card helpers"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.51"
enumset = "1.0.8"
once_cell = "1.8.0"
rand = "0.8.4"
tracing = "0.1.29"

data = { path = "../data", version = "0.0.0" }
