[package]
name = "model"
version = "0.0.0"
description = "Data types used to represent game state"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.51"
strum = "0.23"
strum_macros = "0.23"